filter:
    excluded_paths:
      - 'Tests/*'

build:
    environment:
        php:
            version: 7.2

    tests:
        override:
            -
                command: vendor/bin/simple-phpunit --coverage-clover=coverage-file --coverage-text -v
                coverage:
                    file: coverage-file
                    format: php-clover
