name: Build

on:
  push:
    branches: [ githubci ]
  pull_request:
    branches: [ githubci ]

jobs:
  test:
    name: Test on ${{ matrix.php }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.2', '7.3', '7.4' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run tests
        run: vendor/bin/simple-phpunit -c phpunit.xml.dist
  code-style:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run tests
        run: composer lint:check