name: Build

on:
  push:
    branches: [ githubci ]
  pull_request:
    branches: [ githubci ]

jobs:
  unit-test:
    name: Unit Test [${{ matrix.php }}]
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.2', '7.3', '7.4' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run tests
        run: composer test

  functional-test:
    name: Functional Test [${{ matrix.php }}]
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.2', '7.3', '7.4' ]
    steps:
      - uses: actions/checkout@v2
      - name: Create demo application
        env:
          BRANCH_NAME: ${{ GITHUB_REF }}
        run: |
          composer create-project symfony/symfony-demo --no-install /tmp/symfony-demo && cd /tmp/symfony-demo
          composer config repositories.serializer-bundle path ${GITHUB_WORKSPACE}
          composer config minimum-stability dev
          composer require "tsantos/serializer-bundle:dev-${BRANCH_NAME}" --no-update
          rm -rf composer.lock
          cp ${GITHUB_WORKSPACE}/.travis/PostSerializerCommand.php src/Command
          composer update --prefer-dist --no-interaction --prefer-stable

      - name: Load data fixtures
        run: bin/console doctrine:fixtures:load --no-interaction

      - name: Run demo application
        run: |
          bin/console serializer:generate-hydrators -v --no-interaction
          bin/console serializer:posts --no-interaction

  code-style:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Check style
        run: composer lint:check
